spring.application.name=E-Commerce-Backend

# ==========================
# PostgreSQL Database
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecommerce
spring.datasource.username=postgres
spring.datasource.password=post123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional - Hibernate will detect the dialect automatically
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Disable Flyway
# ==========================
spring.flyway.enabled=false